_BASE_: mask2former_R50_bs16_160k.yaml
DATASETS:
  TRAIN: ("front3d_train",)
  TEST: ("front3d_val",)
MODEL:
  META_ARCHITECTURE: "Uni3D"
  UNI_3D:
    FRUSTUM3D:
      TRUNCATION: 3.0
      ISO_VALUE: 1.0
      PANOPTIC_WEIGHT: 25.0
      COMPLETION_WEIGHTS: [50.0, 25.0, 10.0]
      SURFACE_WEIGHT: 5.0
SOLVER:
  IMS_PER_BATCH: 8
  MAX_ITER: 110000
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: [80000]
INPUT:
  MIN_SIZE_TRAIN: [240]
  MAX_SIZE_TRAIN: 960
  MIN_SIZE_TEST: 240
  MAX_SIZE_TEST: 960
  CROP:
    ENABLED: False
  RANDOM_FLIP: "none"
  DATASET_MAPPER_NAME: "front3d"
